name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc pkg-config libgtk-4-dev libwebkit2gtk-4.0-dev
        
    - name: Build
      run: make build
      
    - name: Test
      run: go test -v ./...
      
    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
